dist: bionic
matrix:
  include:
    - name: fedora
      language: minimal
      services: docker
      install:
        - travis_retry docker build --rm -t CTDContainer -f Dockerfile-fedora .
      script:
        - docker run --rm -t CTDContainer meson build
        - docker run --rm -t CTDContainer ninja -C build
  allow_failures:
  fast_finish: true