dist: bionic
matrix:
  include:
    - name: fedora
      language: minimal
      services: docker
      install:
        - travis_retry docker build --rm -t cdt -f Dockerfile-fedora .
      script:
        - docker run -t cdt /bin/bash -c "meson build;ninja -C build"
  allow_failures:
  fast_finish: true
